from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field


class SearchConfig(BaseModel):
    """Runtime search configuration loaded from TOML."""

    model_config = ConfigDict(
        extra="forbid",
        validate_assignment=True,
        str_strip_whitespace=True,
    )

    prognostic_factor: str = Field(..., min_length=1, description="User-selected prognostic factor.")
    target_population: str = Field(..., min_length=1, description="Population where the factor acts.")
    start_date: str = Field(..., min_length=1, description="Start date in YYYY-MM-DD format.")
    end_date: str = Field(..., min_length=1, description="End date in YYYY-MM-DD format.")
    max_results: int = Field(default=20, ge=1, description="Maximum records requested per source.")


class ArticleRecord(BaseModel):
    """Normalized article record returned by the search agent."""

    model_config = ConfigDict(
        extra="forbid",
        validate_assignment=True,
        str_strip_whitespace=True,
    )

    title: str = Field(..., min_length=1, description="Article title.")
    authors: list[str] = Field(default_factory=list, description="List of author names.")
    journal: str | None = Field(default=None, description="Journal or source title.")
    publication_date: str | None = Field(default=None, description="Publication date as reported by the source.")
    abstract: str | None = Field(default=None, description="Article abstract when available.")
    has_full_text: bool = Field(..., description="Whether full text is directly accessible.")
    full_text_url: str | None = Field(default=None, description="URL to full text when accessible.")


class SearchQueries(BaseModel):
    """Database-specific technical search expressions generated by the agent."""

    model_config = ConfigDict(
        extra="forbid",
        validate_assignment=True,
        str_strip_whitespace=True,
    )

    pubmed_query: str = Field(..., min_length=1)
    embase_query: str = Field(..., min_length=1)
    clinicaltrials_query: str = Field(..., min_length=1)
    ictrp_query: str = Field(..., min_length=1)


class SourceStatus(BaseModel):
    """Execution status for each data source."""

    model_config = ConfigDict(
        extra="forbid",
        validate_assignment=True,
        str_strip_whitespace=True,
    )

    source: str
    query: str
    available: bool
    results_count: int = Field(default=0, ge=0)
    detail: str | None = None


class SearchAgentResult(BaseModel):
    """Final search output with normalized records and per-source status."""

    model_config = ConfigDict(
        extra="forbid",
        validate_assignment=True,
        str_strip_whitespace=True,
    )

    articles: list[ArticleRecord] = Field(default_factory=list)
    source_status: list[SourceStatus] = Field(default_factory=list)
    search_queries: SearchQueries
